from .lazy_prompt_engineer import (
    NODE_CLASS_MAPPINGS as _ENG_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _ENG_NAMES,
)
from .lazy_prompt_describe import (
    NODE_CLASS_MAPPINGS as _VIS_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _VIS_NAMES,
)

NODE_CLASS_MAPPINGS = {**_ENG_CLASSES, **_VIS_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_ENG_NAMES, **_VIS_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
